namespace AndriiCo.TaxCalculatorLib.Entities
{
    /// <summary>
    /// Class to represent currency
    /// </summary>
    public class Currency
    {
        /// <summary>
        ///  Currency name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Symbols that represents currency in an alternative way
        /// </summary>
        public string Symbol { get; set; }

        #region Equals override generated by Resharper
        protected bool Equals(Currency other)
        {
            return string.Equals(Name, other.Name) && string.Equals(Symbol, other.Symbol);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Currency) obj);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return ((Name != null ? Name.GetHashCode() : 0)*397) ^ (Symbol != null ? Symbol.GetHashCode() : 0);
            }
        }
        #endregion
    }
}
